name: Deploy live preview

on:
  push:
    branches: 
      - master

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the PHP Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
        cd api
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master || true
        docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master \
          --target api_platform_php \
          --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master
  build-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Nginx Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
        cd api
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master || true
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master || true
        docker build . \
        --file Dockerfile \
        --tag docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master \
        --target api_platform_nginx \
        --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master \
        --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master

  deploy:
    runs-on: ubuntu-latest
    needs: ['build-php', 'build-nginx']
    steps:
      - name: deploy docker images
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_REF
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: /home/ubuntu/preview-formation/deploy-branch.sh master
