name: Deploy live preview

on:
  pull_request:
    types: [opened, synchronize, reopen]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the PHP Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
        cd api
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master || true
        docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-${{ github.event.pull_request.head.ref }} \
          --target api_platform_php \
          --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-${{ github.event.pull_request.head.ref }}
  build-nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Nginx Docker image
      run: |
        docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
        cd api
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master || true
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master || true
        docker build . \
        --file Dockerfile \
        --tag docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-${{ github.event.pull_request.head.ref }} \
        --target api_platform_nginx \
        --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/php-api-platform:preview-master \
        --cache-from docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-master
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/nginx-api-platform:preview-${{ github.event.pull_request.head.ref }}

  deploy:
    runs-on: ubuntu-latest
    needs: ['build-php', 'build-nginx']
    steps:
      - name: deploy docker images
        uses: appleboy/ssh-action@master
        env:
          BRANCH_REF: ${{ github.event.pull_request.head.ref }}
        with:
          envs: BRANCH_REF
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: GITHUB_REF=$BRANCH_REF /home/ubuntu/preview-formation/deploy-branch.sh
      - name: Post link in comments
        env:
            URL: ${{ github.event.pull_request.comments_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BODY: "⚡️[Preview environment available](https://${{ github.event.pull_request.head.ref }}.preview.theo.do)⚡️"
        run: |
          curl -XGET $URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" | jq -e '.[].body | scan("Preview environment available")' || \
          BODY=$BODY curl --silent -XPOST $URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data "{ \"body\": \"$BODY\" }"
